### ISSUE TITLE
render to string nodejs 

### ISSUE THREAD

**Issue by zebapy** [littlebits/react-popover#34] opened 2015-09-09 00:52 UTC
How can I use this on server side? I get an error as soon as I'm importing since window is undefined

**Comment by jasonkuhrt** [comment] 2015-09-09 12:15
We can certainly make this more server side friendly. As a start we need isomorphic JS such as removing the window dependency. Can you explain your use-case a bit more?

**Comment by gregory90** [comment] 2015-09-13 17:32
Also css-vendor dependency is the problem here(as it depends on window and document objects being available). I'd really like to render react-popover on server as well.
Huge +1.

**Comment by jasonkuhrt** [comment] 2015-09-13 18:22
Ok @sch and I will look at this next week. Thanks for your feedback

**Comment by bkniffler** [comment] 2015-09-20 17:38
+1

**Comment by jasonkuhrt** [comment] 2015-09-20 18:41
I haven't thought hard about this but without access to window I believe most layout options are not workable with popover meaning that it would have to be closed. There are a few layout modes that disregard window in which case it would be feasible to actually render server side. In said other cases we disable it.

**Comment by bkniffler** [comment] 2015-09-21 00:28
Thats okay, most times you'd want to open popovers after user interaction on the client side, so as long as we can use this package in universal apps without errors being thrown, it should be fine.

**Comment by jasonkuhrt** [comment] 2015-09-21 14:34
I made some good progress. There is a dependency issue referenced in the timeline above. Once that is resolved we can close this issue pretty quickly I think.

**Comment by jasonkuhrt** [comment] 2015-09-23 12:25
Update: After discussing with the `css-vendor`author for some time about a patch I'm not convinced about his approach anymore. Two releases and the problem is still not solved. I would prefer to not depend on such a project at this point.

**Closed** 2015-10-02 19:31 UTC
Labels: type / feature
