### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by diegoclearmetal** [littlebits/react-popover#80] opened 2016-08-03 02:02 UTC
Is there a way to easily disable to the popover animation?  I would like the popover to just appear without the fade/fly-in animation...

**Comment by PascalSenn** [comment] 2016-11-05 18:05
made a pullrequest for this: https://github.com/littlebits/react-popover/pull/84

**Comment by oyeanuj** [comment] 2016-12-01 03:53
+1 for this @jasonkuhrt

**Comment by jasonkuhrt** [comment] 2017-01-23 02:36
Thanks for the input everyone. This project is booting back up and I'm listening. No ETAs to share yet but I think something like this should be possible.

**Comment by jasonkuhrt** [comment] 2017-01-23 02:42
Duplicate of #73

**Closed by jasonkuhrt** 2017-01-23 02:42 UTC
Labels: duplicate, feature
